name = "SQLiteFs"
uuid = "9510b5cd-6316-46f5-8bb6-bd7442774278"
authors = ["KlausC <klausC@users.noreply.github.com> and contributors"]
version = "0.1.0"

[deps]
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
